version: "3"

services:
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8080:8080  # Add port mapping to access cAdvisor UI if needed
        networks:
            - monitoring

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        restart: always
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/rootfs"
            - "--collector.filesystem.ignored-mount-points='^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'"
        ports:
            - 9100:9100  # Ensure Node Exporter port is accessible
        networks:
            - monitoring
    blackbox-exporter:
        image: prom/blackbox-exporter:latest
        container_name: blackbox-exporter
        restart: always
        ports:
            - 9115:9115
        networks:
            - monitoring
   
    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        ports:
            - 9093:9093
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        restart: always
        command:
            - "--config.file=/etc/alertmanager/config.yml"

            - "--storage.path=/alertmanager"
        networks:
            - monitoring

    
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        depends_on:
            - cadvisor
            - node-exporter
            - blackbox-exporter
            - alertmanager
        links:
            - alertmanager

        ports:
            - 9090:9090  # Expose Prometheus port for external access
        networks:
            - monitoring

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        volumes:
        volumes:
            # - grafana_data:/var/lib/grafana
            - ./grafana/dashboards:/var/lib/grafana/dashboards
            - ./grafana/provisioning:/etc/grafana/provisioning
        env_file:
            - config.monitoring

        ports:
            - 3000:3000
        depends_on:
            - prometheus
        networks:
            - monitoring

networks:
    monitoring:
